In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [1]:
print("Hello World")

Hello World


In [2]:
value = 200
print(f"hello {value * 2}")
print("hello {}".format(value))

hello 400
hello 200


In [5]:
arr = [1, 3, 2, 4, 5]
numpy_arr = np.array(arr) # numpy.ndarray
print(numpy_arr)

[1 3 2 4 5]


In [ ]:
arr2d = np.array([[5, 6, 7], [4, 2, 3], [1, 2, 3]])
arr2d

array([[5, 6, 7],
       [4, 2, 3],
       [1, 2, 3]])

In [10]:
arr2d.size

9

In [8]:
arr2d.shape

(3, 3)

In [13]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
array3 = np.concatenate([array1[:, np.newaxis], array2[:, np.newaxis]], axis=1)

print(array3.shape)
print(array3)

(3, 2)
[[1 4]
 [2 5]
 [3 6]]


In [22]:
array1 = np.array([1, 2, 3, 4, 5, 6])
array2 = array1.reshape((-1, 1))
print(array2)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [25]:
np.random.randint(0, 256, (256, 256))

array([[ 63, 123,  14, ..., 151,  88,  31],
       [204, 230, 157, ..., 150,  17,  23],
       [138, 153, 124, ...,  91, 151, 170],
       ...,
       [  3, 203, 106, ...,  48, 144,  41],
       [ 90, 111,  47, ...,  21, 163, 245],
       [232,  72,  71, ..., 125, 113, 118]], shape=(256, 256), dtype=int32)

In [27]:
array2 = array1 == 10
array1[array2] = 100

In [28]:
array1

array([1, 2, 3, 4, 5, 6])

In [29]:
array = np.arange(16).reshape(4, 4)
print("최대값:", np.max(array))
print("최소값:", np.min(array))
print("합계:", np.sum(array))
print("평균값:", np.mean(array))

최대값: 15
최소값: 0
합계: 120
평균값: 7.5


In [36]:
array = np.array([5, 9, 10, 3, 1])
array.sort()
print(array[::-1])

[10  9  5  3  1]


In [46]:
array1 = np.array([1, 3, 2])
array2 = np.array([4, 5, 7]).reshape((-1, 1))

In [50]:
array1

array([1, 3, 2])

In [51]:
array2

array([[4],
       [5],
       [7]])

In [47]:
array1 + array2

array([[ 5,  7,  6],
       [ 6,  8,  7],
       [ 8, 10,  9]])