In [1]:
import numpy as np

In [9]:
list_data = [1, 3, 5, 7, 2]
array = np.array(list_data)
array

array([1, 3, 5, 7, 2])

In [ ]:
print(array)

[1 3 5 7 2]


In [5]:
# 배열의 크기(길이) 출력
print(array.size)

5


In [10]:
# 자료형 출력
print(array.dtype)

int64


In [11]:
array[2]

np.int64(5)

In [74]:
array1 = np.arange(9).reshape(3, 3)
array1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
array2 = np.ones((4, 2), dtype= np.float64)
array2

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [73]:
array4 = np.random.randint(0, 10, (3, 3))
array4

array([[5, 7, 3],
       [1, 6, 9],
       [9, 3, 7]], dtype=int32)

In [81]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
array3 = np.concatenate([array1, array2], axis=0)
array3

array([1, 2, 3, 4, 5, 6])

In [84]:
array3 = array3.reshape(2, 3)

In [86]:
array3.shape

(2, 3)

In [94]:
import numpy as np

#left, right = np.split(a, [k], axis=1)   # 왼쪽 k열 / 나머지 / axis = 1 -열기준
#top, bottom = np.split(a, [k], axis=0)   # 위 k행 / 나머지 / axis = 0 -행기준
array = np.arange(8).reshape(2,4)
print(array)
left, right = np.split(array, [1] , axis=1)
print()
print(left)
print()
print(right)

[[0 1 2 3]
 [4 5 6 7]]

[[0]
 [4]]

[[1 2 3]
 [5 6 7]]


In [95]:
array

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [96]:
array + 3

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [97]:
array * 3

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21]])

In [99]:
array1 = np.arange(4).reshape(2, 2)
print(array1)
array2 = np.arange(2)
print("\n", array2)
array3 = array1 + array2
array3

[[0 1]
 [2 3]]

 [0 1]


array([[0, 2],
       [2, 4]])